### ISSUE TITLE
[BUG] JukeBox wont eject after certain distance travelled

### ISSUE THREAD

**Issue by LeoBdt** [jackthehack21/JukeBox-pmmp#2] opened 2019-03-04 22:19 UTC
Hello, when i put a record on a jukebox, it's working perfecly but After ~10s of playing music, i can't drop the record. If i break the jukebox the music won't stop

And only players on W10 can hear the music. If you're on Android or iOS you can't.

**Comment by JaxkDev** [comment] 2019-03-05 07:46
Thank you for the info about sound, I was having trouble to replicate it.

I will have a look into it and try to replicate it, which device have you tried breaking it on after 10secs of music playing ?

**Comment by LeoBdt** [comment] 2019-03-05 08:06
Ok so there is 2 problems : 
1) After ~10-15s of playing song, if i hit the jukebox the music won't stop and i can't have the record back. That's on Windows 10. 
2) All of mobiles (iOS and Android) players on my server can't hear the song.

do you understand?????

**Comment by JaxkDev** [comment] 2019-03-05 08:08
So it won’t give the record back only on windows 10 ?

**Comment by LeoBdt** [comment] 2019-03-05 08:09
no, i've tried with my Galaxy s8 and i can't have the record back too. (and i can't hear the music)

**Comment by JaxkDev** [comment] 2019-03-05 08:11
Hmm, I will try and replicate but the beta testers have all managed to get the disk back but I will get someone on W10,
Thanks for the report.

**Comment by LeoBdt** [comment] 2019-03-05 08:16
did the beta testers can hear the music on mobile device ?

**Comment by LeoBdt** [comment] 2019-03-05 08:17
btw you'r plugin is very optimised and fun. Well done 💪

**Comment by JaxkDev** [comment] 2019-03-05 09:43
No, sound was not heard on neither iPhone or android.
Thanks ❤️

**Comment by LeoBdt** [comment] 2019-03-05 10:23
Look this video is about the record dropping back bug. https://youtu.be/wEir_rSqk2c

**Comment by JaxkDev** [comment] 2019-03-05 11:51
The second time it did drop, the first time I didn’t see it taking in the record.

**Comment by LeoBdt** [comment] 2019-03-05 11:56
Do you want me to make again my video and to record the moment i put the record? 

And as you can see, even if a break the jukebox the music didn't stop

**Comment by JaxkDev** [comment] 2019-03-05 12:55
Could you also provide the server log (picture of console) it should have a lot of info

**Comment by LeoBdt** [comment] 2019-03-05 22:01
i've added custom sound and that's very cool xD

**Comment by LeoBdt** [comment] 2019-03-05 22:05
When i hit the jukebox to have the record back it's says in console "activated" and don't drop the record

**Comment by LeoBdt** [comment] 2019-03-05 23:38
the record disappear after the music is finished

**Comment by JaxkDev** [comment] 2019-03-06 07:24
Need the full log or picture of part where you use jukebox.

**Comment by LeoBdt** [comment] 2019-03-06 11:50
About the problem that only w10 can hear the music, i've found how to solve it. 

A put custom song in a texture pack and it's working. But still can't have cd back, when i hit the jukebox it says "activated", not everytime

**Comment by JaxkDev** [comment] 2019-03-06 12:05
I don’t understand you at all.

**Comment by LeoBdt** [comment] 2019-03-06 12:08
Okay. 

I told you that only w10 can hear record. That was before i put custom music in record file of texture pack. 

For exemple, players Can hear my modified record but not the original record. 

And sometimes, the record doesn't want to get out of jukebox, and it's spamming "activated" in console log.

Is it understandable?

**Comment by JaxkDev** [comment] 2019-03-06 12:17
Spamming activate is a win10 bug that when you click it spams the function.

Could you send the resource pack that makes sound work

And the log of the server.

**Comment by LeoBdt** [comment] 2019-03-06 12:20
Yeah i can. But can you go on my server to see that the record doesn't want to get out of jukebox

networkbe.mcpe.eu 19132

**Comment by JaxkDev** [comment] 2019-03-06 12:36
Will come back on in exactly 2h 30min

For more contact info I’m at gangnam253@gmail.com
Jackthehaxk21#8860 discord

**Comment by LeoBdt** [comment] 2019-03-06 12:38
Okay no problem.

Maybe i can't be here in 2h30min.

But you can go on freebuild server (by hiting the npc), go on a free plot, claim it /p claim and try it by yourself

**Comment by JaxkDev** [comment] 2019-03-06 12:43
I do need the console log at some point to even start tracing it

**Comment by LeoBdt** [comment] 2019-03-06 14:18
Check this https://drive.google.com/file/d/1ekia6GJqdA75t8uO2JMErSWU58ygRhuU/view?usp=drivesdk

And if you have the bug i had in video, when you change level/world, the music is still here

**Comment by JaxkDev** [comment] 2019-03-06 15:17
I do need the console log at some point to even start tracing it

**Comment by LeoBdt** [comment] 2019-03-06 16:01
you can't try on your server?

**Comment by JaxkDev** [comment] 2019-03-06 16:20
I need your server logs as you have WIN10 client which has the spam bug, and have the above problems with it.

**Comment by LeoBdt** [comment] 2019-03-06 16:22
the bug also happened with android.

**Comment by JaxkDev** [comment] 2019-03-06 16:29
Do not reply unless its the server.log
I cannot do very much until i get the important info.

**Comment by LeoBdt** [comment] 2019-03-06 16:32
You want a screenshot?

**Comment by JaxkDev** [comment] 2019-03-06 17:25
Sound not playing on Mobile Devices is fixed (solution said in readme)

This issue is being kept open because of the record not giving back, however its still unconfirmed.
(Still need log)

**Comment by JaxkDev** [comment] 2019-03-06 17:50
Cannot reproduce on Windows 10.

**Comment by LeoBdt** [comment] 2019-03-06 17:52
To reproduce it, put the record in, go a bit far of Juke box and go back to it.

**Comment by LeoBdt** [comment] 2019-03-06 17:54
Can you go on my server? I'll show you the bug

**Comment by SyntaxDragon** [comment] 2019-03-06 18:03
1: he needs the Console log and any errors it produces as has added a debug script into the plugin for this purpose 
2: if you don't know have the error on your console go to your files if your self-hosting and upload your server.log and send the link

He can't help without the console logs otherwise the issue will be Invalid

**Comment by LeoBdt** [comment] 2019-03-06 18:06
There's no error ! i put the record in, it's say 
"adding record
101
playing sound"
and when i try to get the record back it say
"activated"
NOTHING ELSE. I DON'T SEE WHY YOU NEED SERVER.LOG.

**Comment by LeoBdt** [comment] 2019-03-06 18:08
go and check by yourself. 

networkbe.mcpe.eu 19134

**Comment by JaxkDev** [comment] 2019-03-06 18:09
I honestly have no idea why you don't give it, its one of the reason it exists,
Looking into it but now you've said when you go far thats the type of info thats vital,
can now confirm its a bug when going a chunk away and back again.

**Comment by LeoBdt** [comment] 2019-03-06 18:10
thanks.

**Comment by JaxkDev** [comment] 2019-03-08 18:47
Latest commit 3b5fee2 fixes these issues.

**Comment by JaxkDev** [comment] 2019-03-08 18:51
Testing has seen it still exist in some cases, More testing is being done.

**Comment by JaxkDev** [comment] 2019-03-08 19:12
@LeoBdt Issue fixes in the commit mentioned above, v1.0.0 will Be released soon.

**Closed as completed by JaxkDev** 2019-03-08 19:12 UTC
Labels: bug, Status: Resolved

**Comment by JaxkDev** [comment] 2019-03-09 12:42
Released v1.0.0 this issue is now fully fixed.
